dist: xenial
language: java
jdk: openjdk8

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
  sonarcloud:
    organization: "hche608-github"
    token:
      secure: "${sonar}"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'

before_install:
  - java -version
  - google-chrome --version
  - chromedriver --version

script:
#  - mvn clean verify sonar:sonar
  - mvn clean package sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests"
  skip_cleanup: true
  on:
    tags: true